name: CI/CD Budget App

on:
  push:
    branches: [ "main", "feature/dashboard" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test

    - name: Verificar servidor
      run: node server.js & sleep 5